name: tasks
description: "A google Task clone app"

publish_to: 'none'

version: 0.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  freezed_annotation: ^3.0.0
  storage_inspector: ^0.4.0
  drift_local_storage_inspector: ^0.7.0
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

